# Server Configuration
server.port=8080

# SendGrid Configuration
sendgrid.api-key=${SENDGRID_API_KEY}
# Utilisez votre email de l'univ-jfc.fr comme expéditeur
sendgrid.from-email=remi.bastide@univ-jfc.fr
